apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-user-workload-monitoring
  annotations:
    policy.open-cluster-management.io/standards: Monitoring
    policy.open-cluster-management.io/categories: Metrics
    policy.open-cluster-management.io/controls: Prometheus
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-user-workload-monitoring
        spec:
          remediationAction: inform
          severity: high
          object-templates:   
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-monitoring-config
                  namespace: openshift-monitoring
                data:
                  config.yaml: |
                    enableUserWorkload: true
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-user-workload-monitoring
placementRef:
  name: placement-policy-user-workload-monitoring
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-user-workload-monitoring
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-user-workload-monitoring
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: demo
        operator: In
        values:
          - "monitoring"
          - "devops"
          - "all"
