# This policy installs the Advanced Cluster Management Observability functionality
# on the Hub cluster.
# Based on https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.4/html/observability/observing-environments-intro#persistent-stores-observability
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: argocd-petclinic-dev
  annotations:
    policy.open-cluster-management.io/standards: GitOps
    policy.open-cluster-management.io/categories: Application
    policy.open-cluster-management.io/controls: Petclinic DEV
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: acm-observability-namespace
      spec:
        remediationAction: inform
        severity: high
        object-templates:
          - complianceType: musthave
            objectDefinition:
              kind: Application
              apiVersion: argoproj.io/v1alpha1
              metadata:
                annotations:
                  argocd.argoproj.io/sync-wave: "1"
                labels:
                  tenant: petclinic
                  namespace.env: dev
                name: petclinic-dev
              spec:
                destination:
                  namespace: petclinic-dev
                  server: https://kubernetes.default.svc
                project: default
                source:
                  path: gitops/developer/petclinic/overlays/dev
                  repoURL: https://github.com/pittar-demos/roadshow.git
                  targetRevision: main
                syncPolicy:
                  automated:
                    prune: false
                    selfHeal: true
                  retry:
                    limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
                    backoff:
                      duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
                      factor: 2 # a factor to multiply the base duration after each failed retry
                      maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-argocd-petclinic-dev
placementRef:
  name: placement-argocd-petclinic-dev
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: argocd-petclinic-dev
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-argocd-petclinic-dev
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: demo
        operator: In
        values:
          - "petclinic-dev"